### ISSUE TITLE
Bug ao subir o docker

### ISSUE THREAD

**Issue by geich** [ingridflack/products-app#1]
@ingridflack Está dando um bug aqui ao rodar o comando "up":

`unable to prepare context: path "path-to-file/mongo-seed" not found`

Será que não falta algum arquivo para rodar o docker?

**Comment by ingridflack** [comment]
Oi!

Eu atualizei aqui, vi que era um detalhe que eu havia esquecido de remover. Pode testar novamente.

Qualquer coisa é só avisar.
________________________________
De: Gabriel Eich ***@***.***>
Enviado: sexta-feira, 23 de agosto de 2024 14:19
Para: ingridflack/products-app ***@***.***>
Cc: Ingrid Flack ***@***.***>; Mention ***@***.***>
Assunto: [ingridflack/products-app] Bug ao subir o docker (Issue #1)


@ingridflack<https://github.com/ingridflack> Está dando um bug aqui ao rodar o comando "up":

unable to prepare context: path "path-to-file/mongo-seed" not found

Será que não falta algum arquivo para rodar o docker?
